### ISSUE TITLE
java.io.IOException: Cannot connect to hidden service -> An error occurred at task: TakerSendInitTradeRequestToMaker

### ISSUE THREAD

**Issue by slrslr** [haveno-dex/haveno#1727]
In RetoSwap 1.1.0 (.deb) on Linux Debian, I have tried to accept offer:

`An error occurred at task: TakerSendInitTradeRequestToMaker`

Part of the log: https://bin.disroot.org/?cbab45a4b1dfd205#Ft561hmko3R84M8E2KfYNgHApaVcs7XfcVEtomuwXUNM

So when it is an exception, maybe it can show more user friendly message to the user, or any way this can be entirely avoided?

**Comment by woodser** [comment]
It's clearly a connection problem. Does the same error still happen if you try again?

**Comment by woodser** [comment]
Closing as an intermittent connection problem or fixed by https://github.com/haveno-dex/haveno/pull/1782

**Comment by elibroftw** [comment]
Still encountering this type of issue by the way. I walk away from computer, come back and boom someone tried to take my offer, offer gets canned, I have to create a new one.

**Comment by woodser** [comment]
@elibroftw The issue with removing the maker's offer on taker failure is fixed in this PR: https://github.com/haveno-dex/haveno/pull/1919

**Comment by elibroftw** [comment]
Great thanks. I don't believe Reto has released with that yet.
